#!/bin/bash
#SBATCH --job-name={name}
#SBATCH --partition=gpu-shared
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=50G
#SBATCH --account=was215
#SBATCH --no-requeue
#SBATCH -t 48:00:00
#SBATCH --signal=B:USR1@300

module purge
module load gpu
module load slurm
module load amber

HERE=$(pwd)
NVME="/scratch/${USER}/job_${SLURM_JOB_ID}"

cleanup()
{
        echo "cleanup started"
	scancel --signal SIGINT ${SLURM_JOB_ID}
	sleep 30
	echo "moving files back"
        cd $NVME
        tar -cvf files.tar * 2>/dev/null
        cp files.tar $HERE
        cd $HERE
        tar -xf files.tar 2>/dev/null
        rm files.tar
        echo "cleanup finished"
}

trap "cleanup" USR1

genga_func()
{
	echo "Starting simulation"
	srun genga -R -1
	echo "Simulation finished, calling cleanup"
	cleanup
}

echo "Packing up and moving files to NVME"
tar --exclude="slurm-*" -cf files.tar * 2>/dev/null
cp files.tar $NVME
cd $NVME
tar -xf files.tar 2>/dev/null
rm files.tar

genga_func &

wait
